### PR TITLE
upload the model of the resident and managment

### PR DESCRIPTION
**Pull request by sj212131**
created basic file of resident & managment model

### CODE REVIEW

**Comment by sj212131** [comment]
typo

**Comment by sj212131** [comment]
created basic file of resident & management model, typo fixed

**Comment by sj212131** [comment]
fixed typo and added password hash

**Comment by sj212131** [comment]
updated management with password hashed

**Review by ksboyer17 — APPROVED** [review]
Looks Good.

**Review by ksboyer17 — COMMENTED** [review]
Looks Good

**Pull request merged**
